---
- hosts: ios
  gather_facts: no


  tasks:
  - name: "capture existing logging servers"
    ios_command:
      commands:
        - show run | include logging \d+/.\d+/.\d+/.\d+
    register: log_servers
    
  - debug: var=log_servers.stdout_lines
      
  - name: "Remove unnecessary ones"
    ios_config:
      commands: " no {{ item }}"
    when: "'X.X.X.X' not in item"
    loop: "{{ log_servers.stdout_lines[0]}}"
